version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: monitor_api_prod
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=gotyeah
      - DB_PASSWORD=gotyeah_pwd
      - DB_NAME=gotyeah_monitor
    depends_on:
      - db
    networks:
      - monitor_net
    expose:
      - "8000"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: "https://api.monitor.gautierchuinard.com"
    container_name: monitor_front_prod
    restart: unless-stopped
    networks:
      - monitor_net
    expose:
      - "80"

  db:
    image: mysql:8
    container_name: monitor_db_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: gotyeah_monitor
      MYSQL_USER: gotyeah
      MYSQL_PASSWORD: gotyeah_pwd
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monitor_net
    expose:
      - "3306"

volumes:
  db_data:

networks:
  monitor_net:
    name: monitor_net
    external: true
